[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
charcoin = "keyk1FHhXGs82vJ2qecM8Rc96PXVvArVtNfoC8xEyKN"

[programs.devnet]
charcoin = "P62DXPtDL9S68D34mKJ1LNDLRuXSf4Cy63hi5aNVYjR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"  
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
