[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
charcoin = "aUvFTHYrF4N6vpyC5DnkWNXqahcGcDknEScKeoEuANt"

[programs.devnet]
charcoin = "aWuWrrSRxxxZP6mMsLGkQ8kfzBq2FT7K3uEWyHwf4pp"
[programs.mainnet]
charcoin = "c37mvW9JM6S3bzsY43VhJWQucW1b8uFyBkK4y3LCdRH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"  
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
